import unittest

from main import find_index_of_the_darkest_street_light


class Find_index_of_the_darkest_street_light(unittest.TestCase):
    def test_find_index_of_the_darkest_street_light(self):
        self.assertEqual(find_index_of_the_darkest_street_light(200, [4, 5, 6]), 5)
        self.assertEqual(
            find_index_of_the_darkest_street_light(
                5000,
                [
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                ],
            ),
            14,
        )
        self.assertEqual(
            find_index_of_the_darkest_street_light(
                5000,
                [
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    104,
                    105,
                    106,
                    107,
                    108,
                    109,
                    110,
                    111,
                    112,
                    113,
                    114,
                    115,
                    116,
                    117,
                    118,
                    119,
                    120,
                    121,
                    122,
                    123,
                    124,
                    125,
                    126,
                    127,
                    128,
                    129,
                    130,
                ],
            ),
            14,
        )
        self.assertEqual(find_index_of_the_darkest_street_light(200, [4, "a", 6]), {})


if __name__ == "__main__":
    unittest.main()
